// <auto-generated />
using CoreFoodProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreFoodProject.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240512124805_createDataBase")]
    partial class createDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreFoodProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("varchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CoreFoodProject.Models.Foot", b =>
                {
                    b.Property<int>("FootId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("FootImageURl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FootLongDescription")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FootName")
                        .HasColumnType("varchar(50)");

                    b.Property<double>("FootPrice")
                        .HasColumnType("float");

                    b.Property<string>("FootShortDescription")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("FootStock")
                        .HasColumnType("int");

                    b.Property<string>("FootThumbNailImageneURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FootId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("CoreFoodProject.Models.Foot", b =>
                {
                    b.HasOne("CoreFoodProject.Models.Category", "Category")
                        .WithMany("Foots")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoreFoodProject.Models.Category", b =>
                {
                    b.Navigation("Foots");
                });
#pragma warning restore 612, 618
        }
    }
}
